import React from "react";
import { Header } from "./Header";
import Head from "next/head";
import TodoApp from "../TodoApp";

export const Layout: React.FC = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/public/favicon.ico" />
            </Head>
            <div className="flex min-h-screen flex-col">
                <Header />
                {children}
            </div>
        </>
    )
}