import React from "react";
import {Header} from "./Header";
import Head from "next/head";
import {BottomNav} from "./BottomNav";

export const Layout = ({children,}: {
    children: React.ReactNode
}) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/public/favicon.ico"/>
            </Head>
            <div className="flex min-h-screen flex-col bg-gray-50 dark:bg-gray-900">
                <Header/>
                {children}
                <BottomNav/>
            </div>
        </>
    )
}